### ISSUE TITLE
When I run BotDigger with sample pcap I get error

### ISSUE THREAD

**Issue by rajnmithun** [hanzhang0116/BotDigger#4]
```
Traceback (most recent call last):
  File "BotDigger.py", line 1608, in <module>
    main(sys.argv[1:])
  File "BotDigger.py", line 1559, in main
    singlePcapDetection(pc, fpOutput, dnsServerDict, networkPrefixDict)
  File "BotDigger.py", line 1224, in singlePcapDetection
    updateResponseDomain(hostDict, qname.name, qname.type, dns.rcode, ip, ts, domainIP, fpOutput)
  File "BotDigger.py", line 678, in updateResponseDomain
    suspiciousDomain = labelSuspiciousDomain(domain, tldDict, ccTldDict)
  File "BotDigger.py", line 425, in labelSuspiciousDomain
    (typoDomain, distance) = distanceDomain(domain, popularDomainDict, ccTldDict, tldDict)
  File "BotDigger.py", line 280, in distanceDomain
    if Levenshtein.distance(domain2LD, popularDomain) < minDistance:
TypeError: distance expected two Strings or two Unicodes
```

**Comment by cardi** [comment]
Can you verify that you're running the latest version of BotDigger by updating your repository to the latest version?

Are you running the provided sample call script?

~~~~
python BotDigger.py \
  -B 4 -T 0.10 -w 300 \
  -P NetworkPrefixes -s DNSServerList -t TLDList -b OverloadDNSWebsites \
  -c InvalidWords -p top-1m.csv -d wordsEn.txt -e BigCompanies \
  -x ExculedHosts -D ExculedDomains -n DynamicDomains \
  -f bot_sample.pcap \
  -r bot_sample-results.txt
~~~~

**Comment by rajnmithun** [comment]
I am running on the latest checkout from `master` branch. I ran `PackagesInstallation.sh` and then
```
python BotDigger.py \
                       -B 4 -T 0.10 -w 300 \
                       -P NetworkPrefixes -s DNSServerList -t TLDList -b OverloadDNSWebsites \
                       -c InvalidWords -p top-1m.csv -d wordsEn.txt -e BigCompanies \
                       -x ExculedHosts -D ExculedDomains -n DynamicDomains \
                       -f bot_sample.pcap \
                       -r bot_sample-results.txt
Traceback (most recent call last):
  File "BotDigger.py", line 1606, in <module>
    main(sys.argv[1:])
  File "BotDigger.py", line 1557, in main
    singlePcapDetection(pc, fpOutput, dnsServerDict, networkPrefixDict)
  File "BotDigger.py", line 1222, in singlePcapDetection
    updateResponseDomain(hostDict, qname.name, qname.type, dns.rcode, ip, ts, domainIP, fpOutput)
  File "BotDigger.py", line 676, in updateResponseDomain
    suspiciousDomain = labelSuspiciousDomain(domain, tldDict, ccTldDict)
  File "BotDigger.py", line 423, in labelSuspiciousDomain
    (typoDomain, distance) = distanceDomain(domain, popularDomainDict, ccTldDict, tldDict)
  File "BotDigger.py", line 278, in distanceDomain
    if Levenshtein.distance(domain2LD, popularDomain) < minDistance:
TypeError: distance expected two Strings or two Unicodes
```

**Comment by cardi** [comment]
I just tested with a fresh checkout and it works for me. Can you verify the versions of Python and packages you're using?

~~~~
$ python --version
Python 2.7.13
$ pip show python-levenshtein
Name: python-Levenshtein
Version: 0.12.0
...
~~~~

**Comment by rajnmithun** [comment]
```
BotDigger · master ⟩ python --version
Python 2.7.13
BotDigger · master ⟩ pip show python-levenshtein
Name: python-Levenshtein
Version: 0.12.0
Summary: Python extension for computing string edit distances and similarities.
Home-page: http://github.com/ztane/python-Levenshtein
Author: Antti Haapala
Author-email: antti@haapala.name
License: GPL
...
```

**Comment by rajnmithun** [comment]
```
BotDigger · master ⟩ pip list --format=columns
Package            Version
------------------ -------
dnslib             0.9.7
dpkt               1.9.0
mercurial          4.1.1
netaddr            0.7.19
numpy              1.12.1
pip                9.0.1
pylzma             0.4.8
pypcap             1.1.5
python-Levenshtein 0.12.0
pythonwhois        2.4.3
setuptools         32.1.0
wheel              0.29.0
wordsegment        0.8.0
```

**Comment by cardi** [comment]
From what I can tell it looks like somewhere in the processing pipeline some strings (containing domains) are being stored as `unicode` while some others are `ascii`.

I can't tell which one is causing you problems, but it might be related to the default encoding. Can you run the following?

~~~~
$ python -c 'import sys; print(sys.getdefaultencoding())'
ascii
~~~~

**Comment by rajnmithun** [comment]
```
BotDigger · master ⟩ python -c 'import sys; print(sys.getdefaultencoding())'
ascii
```

**Comment by cardi** [comment]
I'm out of ideas at the moment. Pinging @hanzhang0116 if he has any suggestions or fixes–a possible improvement is to switch all processing to be `unicode`-friendly.

@rajnmithun you might want to try looking at this [StackOverflow post][so] to change the default encoding of Python to force it to `ascii` or `UTF8` and see what happens.

also, before you change the encoding, could you try some of these print debugging statements right before [BotDigger.py:278][bd278]
~~~~
print "type %s, value: %s" % (type(domain2LD), domain2LD)
print "type %s, value: %s" % (type(popularDomain), popularDomain)
~~~~
and see what outputs? (You will get a lot of output).

[so]: https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python
[bd278]: https://github.com/hanzhang0116/BotDigger/blob/8bdcd69a2eff5410c14972c549bd218ccc4de1e4/BotDigger.py#L278

**Comment by cardi** [comment]
@rajnmithun I ran into this issue again while testing BotDigger on Ubuntu 16.04 LTS (I didn't run into this issue using Fedora Core 24). I'm not quite sure what changed, but I'm pushing a fix that will pass `utf-8` Unicode strings to the distance function.
