### ISSUE TITLE
when i run runsample.sh , i get this error . Any suggestions plz

### ISSUE THREAD

**Issue by khegul** [hanzhang0116/BotDigger#5]
~/BotDigger-master$ ./RunSample.sh
bot_sample.pcap
Traceback (most recent call last):
  File "BotDigger.py", line 1607, in <module>
    main(sys.argv[1:])
  File "BotDigger.py", line 1560, in main
    timeoutDetection(hostDict, fpOutput)
  File "BotDigger.py", line 1283, in timeoutDetection
    botDetection(hostDict[ip], fpOutput)
  File "BotDigger.py", line 748, in botDetection
    domainAttributes = extractAttributes(domains[index], ccTldDict, tldDict, fpOutput)
  File "BotDigger.py", line 549, in extractAttributes
    meaningfulWordsLength2LD = wordBreak(domain2LD, dictionaryDict)
  File "BotDigger.py", line 482, in wordBreak
    info = segment(word)
  File "/home/csrc/.local/lib/python2.7/site-packages/wordsegment/__init__.py", line 159, in segment
    return list(self.isegment(text))
  File "/home/csrc/.local/lib/python2.7/site-packages/wordsegment/__init__.py", line 145, in isegment
    _, chunk_words = search(prefix + chunk)
ValueError: need more than 0 values to unpack

**Comment by cardi** [comment]
It looks like the `wordsegment` package has been updated to 1.1.6, breaking some things in BotDigger in the process.

Your best bet is to install the version that we've been using in our development, 0.6.2. Try the following:

```
pip uninstall --user wordsegment
pip install --user wordsegment==0.6.2
```

Can you give that a try and run `RunSample.sh` again?

For future reference, these are the Python module versions that are known to work with BotDigger:

```
$ pip freeze | egrep "(wordsegment|python-Levenshtein|pythonwhois|dpkt|pypcap|netaddr|dnslib|pylzma)"
dnslib==0.9.6
dpkt==1.8.8
netaddr==0.7.18
pylzma==0.4.8
pypcap==1.1.5
python-Levenshtein==0.12.0
pythonwhois==2.4.3
wordsegment==0.6.2
```

I'll fix this up shortly with a `requirements.txt` file.
